[package]
name = "imagefmt"
version = "0.1.1"
authors = ["Tero Hänninen"]
description = "PNG, TGA and JPEG (no encoder for JPEG). 8-bit only, with conversions."
license = "MIT"
repository = "https://github.com/lgvz/imagefmt"
include = ["imagefmt.rs", "Cargo.toml", "README.md"]

[lib]
name = "imagefmt"
path = "imagefmt.rs"

[dependencies]
flate2 = "0.2"
