[package]
name = "imagefmt"
version = "0.2.0"
authors = ["Tero Hänninen"]
description = "PNG, TGA and JPEG (no encoder for JPEG). 8-bit only, with conversions."
license = "MIT"
repository = "https://github.com/lgvz/imagefmt"

[lib]
name = "imagefmt"
path = "imagefmt.rs"

[dependencies]
flate2 = "0.2"
