[package]
name = "imagefmt"
version = "0.3.0"
authors = ["Tero Hänninen"]
description = "Decoders for PNG, TGA, BMP, JPEG. Encoders for PNG, TGA. 8-bit only, with conversions."
license = "MIT"
repository = "https://github.com/lgvz/imagefmt"

[dependencies]
flate2 = "0.2"
