[package]
name = "imagefmt"
version = "0.4.0"
authors = ["Tero Hänninen"]
description = "Decoders for PNG, TGA, BMP, JPEG. Encoders for PNG, TGA. 8-bit only, with conversions."
license = "MIT"
include = ["src/*", "Cargo.toml", "README.md"]
repository = "https://github.com/lgvz/imagefmt"
documentation = "http://lgvz.github.io/imagefmt/imagefmt/"

[dependencies]
flate2 = "0.2"
