[package]
name = "imagefmt"
version = "0.5.0"
authors = ["Tero Hänninen"]
description = "Decoders for PNG, TGA, BMP, JPEG. Encoders for PNG, TGA. 8-bit only, with conversions."
license = "MIT"
include = ["src/*", "Cargo.toml", "README.md", "Makefile"]
repository = "https://github.com/lgvz/imagefmt"
documentation = "http://lgvz.github.io/imagefmt/imagefmt/"

[features]
default = ["png", "jpeg", "bmp", "tga"]
png = []
jpeg = []
bmp = []
tga = []

[dependencies]
flate2 = "0.2"
